language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t clementsorano/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true clementsorano/docker-react npm run test