language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t clementsorano/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true clementsorano/docker-react npm run test

# Exemple
# deploy:
  #provider: elasticbeanstalk
  #region: "us-west-2"
  #app: "docker"
  #env: "Docker-env"
  #bucket_name: "elasticbeanstalk-us-west-2-0000000000"
  #bucket_path: "docker"
  #on:
    #branch: master
  #access_key_id: $AWS_ACCESS_KEY
  #secret_access_key: $AWS_SECRET_KEY